[target.'cfg(target_os = "vexos")']
rustflags = ["-Clink-arg=-Tvexide.ld"]

[target.x86_64-pc-windows-msvc.freetype]
rustc-link-search = [
    "C:\\Users\\Nasir\\Documents\\Code\\vcpkg\\installed\\x64-windows\\bin",
    "C:\\Users\\Nasir\\Documents\\Code\\vcpkg\\installed\\x64-windows\\lib"
]
rustc-link-lib = ["freetype"]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]
